name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 15.x

      - name: Install Dependencies
        run: npm ci

      - name: Test Project
        run: npm test

      - name: Build Project
        run: npm run build
        env:
          CI: false

      - name: Deploy to Firebase Hosting
        if: ${{ github.event_name == 'push' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TUTORLITE_32CE8 }}"
          channelId: live
          projectId: tutorlite-32ce8
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Preview Website
        if: ${{ github.event_name == 'pull_request' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TUTORLITE_32CE8 }}"
          projectId: tutorlite-32ce8
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
